title: Code Examples
description: Programing Language Code Example Site

theme: null

# debug:
#   compress: true
#   dist: false
#   shortcodes: true

google:
  adsense: ca-pub-1277792897041775
  gtag: UA-144729693-1

readme_index:
  with_frontmatter: true

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - Makefile
  - CNAME
  - LICENSE
  - update.sh
  - Gemfile
  - Gemfile.lock
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - jekyll-rtd-theme.gemspec
